name: alerta_criminal
description: "be aware about crims in your city"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-259.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  google_maps_flutter: ^2.6.1
  envied: ^0.5.4+1
  location: ^6.0.2
  image_picker: ^1.1.2
  uuid: ^4.4.2
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  get_it: ^7.7.0
  email_validator: ^3.0.0
  cloud_firestore: ^4.17.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.2
  localstorage: ^5.0.0
  validadores: ^1.0.9
  skeletonizer: ^1.4.2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#161629"
#  image: assets/app_icon.png

  android_12:
#    image: assets/alerta-criminal-splash-image.png
    color: "#161629"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"

flutter:
  generate: true
  uses-material-design: true
