name: alerta_criminal
description: "be aware about crims in your city"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-259.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  google_maps_flutter: ^2.10.0
  envied: ^1.0.0
  location: ^7.0.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  firebase_storage: ^12.3.7
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  get_it: ^8.0.3
  email_validator: ^3.0.0
  cloud_firestore: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  http: ^1.2.2
  localstorage: ^5.0.0
  validadores: ^1.0.9
  skeletonizer: ^1.4.2
  transparent_image: ^2.0.1
  font_awesome_flutter: ^10.8.0

  flutter_native_splash: any
  google_maps_flutter_platform_interface: any
  firebase_app_check: ^0.3.1+7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  source_gen: ^1.2.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  color: "#161629"
#  image: assets/app_icon.png

  android_12:
#    image: assets/alerta-criminal-splash-image.png
    color: "#161629"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
